GET http://localhost:8000/

###
GET http://localhost:8000/notfound

###
POST http://localhost:8000/api/v1/user/register
Content-Type: application/json

{
    "name": "ekram ullah",
    "email": "ekramullah70@gmail.com",
    "password": "aaa#a2Ux"
}

###
GET http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email": "ekramullah70@gmail.com",
    "password": "aaa#a2Ux"
}